spring:
  application:
    name: alimurph-postcard

server:
  port: 8088
  servlet:
    context-path: /api/v1/

application:
  security:
    card:
      secret-key: ${ALIMURPH_POSTCARD_SECRET_KEY}
  frontend:
    url: ${ALIMURPH_POSTCARD_FRONTEND_URL}
  assets:
    path: ${ALIMURPH_POSTCARD_ASSETS_PATH}


logging:
  level:
    root: ERROR